global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:80"]

  - job_name: "activity"
    static_configs:
      - targets: ["activity:5300"]

  - job_name: "analytics"
    static_configs:
      - targets: ["analytics:5050"]

  - job_name: "auth"
    static_configs:
      - targets: ["auth:8080"]
    metrics_path: "/actuator/prometheus"
