name: Deploy AuthService to AWS ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "authservice/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"

      # Navigate to authservice directory
      - name: Change to authservice directory
        run: cd authservice

      # Run Gradle tests
      - name: Run Gradle tests
        run: ./gradlew clean test

      # Configuring AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build, tag, and push image for AuthService
      - name: Build, tag, and push image to Amazon ECR (AuthService)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mla-fitnessapp-authservice
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
